# Generated by Django 5.2.4 on 2025-08-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='maintenanceQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
