# Generated by Django 5.2.4 on 2025-08-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_maintenancequantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='maintenanceQuantity',
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
