# Generated by GitHub Copilot
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_remove_asset_maintenancequantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="maintenance_quantity",
        ),
        migrations.AddField(
            model_name="asset",
            name="maintenance_schedule",
            field=models.CharField(blank=True, choices=[("Monthly", "Monthly"), ("Quarterly", "Quarterly"), ("Half-Yearly", "Half-Yearly"), ("Yearly", "Yearly")], max_length=20),
        ),
    ]
